{
 "title": "helia-http-gateway default dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "heatmap_buckets", "query": "${VAR_HEATMAP_BUCKETS}" },
   { "name": "axisWidth", "query": "${VAR_AXISWIDTH}" }
  ]
 },
 "panels": [
  { "title": "Helia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bitswap Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "helia_bitswap_peers", "legendFormat": "Peers" }
   ]
  },
  {
   "title": "Bitswap Message Send Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "helia_bitswap_message_send_queue",
     "legendFormat": "{{helia_bitswap_message_send_queue}}"
    }
   ]
  },
  { "title": "js-libp2p", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "libp2p_connection_manager_connections",
     "legendFormat": "{{libp2p_connection_manager_connections}}"
    }
   ]
  },
  {
   "title": "Dial Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "libp2p_dial_queue", "legendFormat": "{{libp2p_dial_queue}}" }
   ]
  },
  {
   "title": "Protocol Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "libp2p_protocol_streams_total", "legendFormat": "{{protocol}}" }
   ]
  },
  {
   "title": "Data transfer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(libp2p_data_transfer_bytes_total[$__rate_interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "TCP Dialer Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(libp2p_tcp_dialer_events_total[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "Noise", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Decrypt Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(libp2p_noise_decrypt_errors_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "XX Handshake Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(libp2p_noise_xxhandshake_error_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "KAD-DHT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Query Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "libp2p_kad_dht_query_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    { "expr": "libp2p_kad_dht_ping_queue", "legendFormat": "{{libp2p_kad_dht_ping_queue}}" }
   ]
  },
  {
   "title": "Message Send Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "libp2p_kad_dht_network_message_send_times_milliseconds",
     "legendFormat": "{{libp2p_kad_dht_network_message_send_times_milliseconds}}"
    }
   ]
  },
  { "title": "NodeJS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nodejs_memory_usage_bytes", "legendFormat": "{{memory}}" }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval]) * 100",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total[$__rate_interval]) * 100",
     "legendFormat": "System"
    },
    {
     "expr": "rate(process_cpu_user_seconds_total[$__rate_interval]) * 100",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    { "expr": "nodejs_active_handles", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_mean_seconds",
     "legendFormat": "mean"
    },
    {
     "expr": "nodejs_eventloop_lag_max_seconds",
     "legendFormat": "max"
    },
    {
     "expr": "nodejs_eventloop_lag_min_seconds",
     "legendFormat": "min"
    }
   ]
  }
 ]
}